version: "3.9"

# This is a CI-specific override for your docker-compose configuration
# It removes problematic mounts and security configurations that don't work in GitHub Actions

services:
  infra:
    volumes:
      # Remove problematic proc and sys mounts
      # - /proc:/host/proc:ro
      # - /sys:/host/sys:ro
      - ./config/newrelic-infra.yml:/etc/newrelic-infra.yml:ro
    security_opt:
      - seccomp=unconfined  # Disable seccomp profiles
    # Add this environment variable to indicate test mode
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NRIA_VERBOSE: 1
      CI_TEST_MODE: true

  otel:
    volumes:
      # Remove problematic proc and sys mounts
      # - /proc:/host/proc:ro
      # - /sys:/host/sys:ro
      - ./config/otel-config.yaml:/etc/otel-config.yaml:ro
    security_opt:
      - seccomp=unconfined  # Disable seccomp profiles
    # Add this environment variable to indicate test mode
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      CI_TEST_MODE: true

  otel-docker:
    volumes:
      # Remove problematic proc and sys mounts
      # - /proc:/host/proc:ro
      # - /sys:/host/sys:ro
      - ./config/otel-config.yaml:/etc/otel-config.yaml:ro
      # Remove Docker socket mount
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - seccomp=unconfined  # Disable seccomp profiles
    # Add this environment variable to indicate test mode
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      CI_TEST_MODE: true

  load:
    security_opt:
      - seccomp=unconfined  # Disable seccomp profiles
    # Add this environment variable to indicate test mode  
    environment:
      STRESS_CPU: ${STRESS_CPU:-2}
      STRESS_MEM: ${STRESS_MEM:-128M}
      CI_TEST_MODE: true