version: "3.9"

services:
  infra:
    image: newrelic/infrastructure:latest
    container_name: nr-infra
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NRIA_VERBOSE: 1
    cap_add: [SYS_PTRACE, DAC_READ_SEARCH]
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./config/newrelic-infra.yml:/etc/newrelic-infra.yml:ro
    tmpfs:
      - /tmp
      - /var/run
      - /var/db/newrelic-infra
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18003/status", "||", "exit", "1"]
      interval: 10s
      retries: 5
    restart: unless-stopped
    security_opt:
      - ${SECURE_MODE:+seccomp:./profiles/seccomp-nr.json}
    deploy:
      resources:
        limits:
          memory: 512M
    profiles: ["bare-agent"]

  load:
    build: ./load-image
    container_name: stress-load
    user: "1000:1000"
    entrypoint: ["/entrypoint.sh"]
    environment:
      STRESS_CPU: ${STRESS_CPU:-2}
      STRESS_MEM: ${STRESS_MEM:-128M}
    tmpfs:
      - /tmp
      - /var/run
    deploy:
      resources:
        limits: {cpus: "1.5", memory: 512M}
    healthcheck:
      test: ["CMD-SHELL", "pidof stress-ng || exit 1"]
      interval: 10s
      retries: 3
    restart: unless-stopped
    profiles: ["bare-agent"]