# ProcessSample Filter Definitions
# Central location for all filter patterns

# NONE: No filtering (baseline for comparison)
none: {}

# STANDARD: Basic system process filtering
standard:
  process.systemd.*: true
  process.kworker.*: true
  process.kthreadd.*: true
  process.rcu.*: true
  process.migration.*: true
  process.ksoftirqd.*: true
  process.sshd.*: true
  process.chronyd.*: true
  process.crond.*: true
  process.upstart.*: true
  process.init.*: true
  process.lsmd.*: true
  process.systemd-journal.*: true
  process.dbus-daemon.*: true
  process.atd.*: true
  process.lvmetad.*: true
  process.smartd.*: true
  process.iscsid.*: true
  process.gssproxy.*: true
  process.bash.cpu.user: true
  process.bash.cpu.system: true
  process.bash.memory.rss: true

# AGGRESSIVE: Maximum filtering
aggressive:
  process.systemd.*: true
  process.kworker.*: true
  process.kthreadd.*: true
  process.rcu.*: true
  process.migration.*: true
  process.ksoftirqd.*: true
  process.sshd.*: true
  process.chronyd.*: true
  process.crond.*: true
  process.upstart.*: true
  process.init.*: true
  process.lsmd.*: true
  process.systemd-journal.*: true
  process.dbus-daemon.*: true
  process.atd.*: true
  process.lvmetad.*: true
  process.smartd.*: true
  process.iscsid.*: true
  process.gssproxy.*: true
  process.bash.*: true
  process.syslogd.*: true
  process.rsyslogd.*: true
  process.gvfs.*: true
  process.dnsmasq.*: true
  process.polkit.*: true
  process.networkd.*: true
  process.networkmanager.*: true
  process.cupsd.*: true
  process.avahi.*: true
  process.rpcbind.*: true
  process.postfix.*: true
  process.agetty.*: true
  process.ntpdate.*: true
  process.dhclient.*: true
  process.multipathd.*: true
  process.tuned.*: true
  process.lvm.*: true
  process.nfsiod.*: true
  process.ps.*: true
  process.sudo.*: true
  process.snapd.*: true
  process.polkitd.*: true
  process.libvirtd.*: true
  process.cron.*: true
  process.crontab.*: true
  process.getty.*: true
  process.dconf.*: true
  process.rtkit.*: true
  process.tpm.*: true
  process.acpid.*: true
  process.login.*: true
  process.mount.*: true
  process.automount.*: true
  process.uuidd.*: true
  process.fwupd.*: true
  process.gdm.*: true
  process.apt.*: true
  process.yum.*: true
  process.dnf.*: true
  process.dpkg.*: true
  process.rpm.*: true

# TARGETED: Only include specific processes (whitelist approach)
targeted:
  # Block everything by default
  process.*.cpu.*: true
  process.*.memory.*: true
  # Allow specific processes
  process.apache*.cpu.*: false
  process.apache*.memory.*: false
  process.nginx*.cpu.*: false
  process.nginx*.memory.*: false
  process.mysql*.cpu.*: false
  process.mysql*.memory.*: false
  process.postgres*.cpu.*: false
  process.postgres*.memory.*: false
  process.mongo*.cpu.*: false
  process.mongo*.memory.*: false
  process.redis*.cpu.*: false
  process.redis*.memory.*: false
  process.java*.cpu.*: false
  process.java*.memory.*: false
  process.node*.cpu.*: false
  process.node*.memory.*: false
  process.python*.cpu.*: false
  process.python*.memory.*: false
  process.docker*.cpu.*: false
  process.docker*.memory.*: false
  process.stress-ng*.cpu.*: false
  process.stress-ng*.memory.*: false