license_key: ${NEW_RELIC_LICENSE_KEY}
enable_process_metrics: true
metrics_process_sample_rate: ${SAMPLE:-60}
collect_process_commandline: false

# Targeted filtering using include block
include_matching_metrics:
  process.name: ["my-app-*", "stress-ng"]  # Only include these processes
