# New Relic Infrastructure Agent - ProcessSample Optimization Template
# Runtime generation based on FILTER_TYPE and SAMPLE_RATE

license_key: $NEW_RELIC_LICENSE_KEY

# ProcessSample optimization settings (configured via environment variables)
metrics_process_sample_rate: ${SAMPLE_RATE}  # Default: 60s interval
collect_command_line: ${COLLECT_CMDLINE}     # Default: false

# Standard settings
collect_inventory_interval: 30
plugins_auto_update: false
log_file: "/var/log/newrelic-infra/newrelic-infra.log"
verbose: 1

# Process filtering configuration - will be replaced during runtime generation
exclude_matching_metrics:
  # FILTER_PATTERNS
