# New Relic Infrastructure Agent - ProcessSample Optimization Template
# Runtime generation based on FILTER_TYPE and SAMPLE_RATE

license_key: $NEW_RELIC_LICENSE_KEY

# ProcessSample optimization settings (configured via environment variables)
metrics_process_sample_rate: 60  # Default: 60s interval
collect_command_line: false     # Default: false

# Standard settings
collect_inventory_interval: 30
plugins_auto_update: false
log_file: "/var/log/newrelic-infra/newrelic-infra.log"
verbose: 1

# Process filtering configuration - will be replaced during runtime generation
exclude_matching_metrics:
  process.atd.*: true
  process.bash.cpu.system: true
  process.bash.cpu.user: true
  process.bash.memory.rss: true
  process.chronyd.*: true
  process.crond.*: true
  process.dbus-daemon.*: true
  process.gssproxy.*: true
  process.init.*: true
  process.iscsid.*: true
  process.ksoftirqd.*: true
  process.kthreadd.*: true
  process.kworker.*: true
  process.lsmd.*: true
  process.lvmetad.*: true
  process.migration.*: true
  process.rcu.*: true
  process.smartd.*: true
  process.sshd.*: true
  process.systemd-journal.*: true
  process.systemd.*: true
  process.upstart.*: true
