extensions:
  health_check: {}
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:
      load:
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 10s
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
  filter/core-metrics:
    metrics:
      include:
        match_type: regexp
        metric_names: ["^system\\.(cpu|memory|disk|filesystem|network|load)\\..*"]
  batch: {}
exporters:
  otlp:
    endpoint: "otlp.nr-data.net:4317"
    headers:
      api-key: "${NEW_RELIC_LICENSE_KEY}"
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [hostmetrics, docker_stats]
      processors: [memory_limiter, filter/core-metrics, batch]
      exporters: [otlp]