receivers:
  hostmetrics:
    collection_interval: ${INTERVAL}
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
      process:
        mute_process_name_error: true
        metrics:
          process.cpu.utilization:
            enabled: true

  # Docker metrics - will be enabled conditionally based on ENABLE_DOCKER_STATS
  # DOCKER_RECEIVER

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  resource:
    attributes:
      - key: service.name
        value: "process-lab-otel"
        action: upsert
      - key: service.instance.id
        value: "${HOSTNAME}"
        action: upsert

  metricstransform:
    transforms:
      - include: system.cpu.utilization
        action: update
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: [ cpu ]

      - include: system.memory.utilization
        action: update
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: [ state ]

exporters:
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

  logging:
    verbosity: normal

service:
  pipelines:
    metrics:
      receivers: [hostmetrics] # DOCKER_PIPELINE
      processors: [resource, metricstransform, batch]
      exporters: [otlp, logging]

  telemetry:
    logs:
      level: info
    metrics:
      level: normal