version: '3.8'

# Unified Docker Compose file for ProcessSample Optimization Lab
# Environment variables control all variations:
#   FILTER_TYPE: none, standard, aggressive, targeted
#   SAMPLE_RATE: 20, 30, 60, 90, 120
#   ENABLE_DOCKER_STATS: true/false
#   OTEL_INTERVAL: 5s, 10s, 20s, 30s
#   ENABLE_PROCESS_METRICS: true/false
#   OTEL_LOG_LEVEL: info, debug, warn

services:
  # New Relic Infrastructure Agent with ProcessSample optimization
  infra-agent:
    image: newrelic/infrastructure:latest
    container_name: nr-infra-agent
    hostname: nr-process-lab
    volumes:
      # Dynamic mount based on filter type - gets populated by process_lab.py
      - ${PWD}/config/newrelic-infra.yml:/etc/newrelic-infra.yml:ro
      - ${PWD}/results:/var/log/newrelic-infra
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/host:ro
    environment:
      - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NRIA_DISPLAY_NAME=Process Optimization Lab
    cap_add:
      - SYS_PTRACE
    
    networks:
      - process-lab
    depends_on:
      - load-generator
      
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    hostname: otel-collector
    volumes:
      - ${PWD}/config/otel-config.yaml:/etc/otelcol-contrib/config.yaml:ro
     
      # Host mount for metrics
      - /:/host:ro
      - ${ENABLE_DOCKER_STATS:+/var/run/docker.sock:/var/run/docker.sock:ro}
    
    networks:
      - process-lab
    depends_on:
      - infra-agent

  # Load Generator
  load-generator:
    image: polinux/stress-ng:latest
    container_name: load-generator
    hostname: load-generator
    command: >
      --cpu ${STRESS_CPU:-2} 
      --vm ${STRESS_VM:-1} 
      --vm-bytes ${STRESS_MEM:-256M} 
      ${STRESS_IO:+--io ${STRESS_IO}} 
      --timeout 0
    networks:
      - process-lab

networks:
  process-lab:
    driver: bridge