name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          check_together: 'yes'
          scandir: './scripts'

  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"
          config: '.markdownlint.json'

  link-check:
    name: Check markdown links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: '--verbose --no-progress "**/*.md" --exclude "http://127.0.0.1*" --exclude "file:///*"'
          fail: true

  trivy:
    name: Security scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build load image
        run: docker build -t infra-lab-load:test ./load-image
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'infra-lab-load:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'